ignore:
  - '__tests__/**/*'
  - '.depcheckrc'
  - '.env*'
  - '.eslint*'
  - '.github/**/*'
  - '.gitignore'
  - '.husky/**/*'
  - '.prettier*'
  - '.scripts/**/*'
  - '.tool-versions'
  - '.vscode/**/*'
  - '*.json'
  - '*.md'
  - 'codecov.yml'
  - 'coverage/**/*'
  - 'Dockerfile'
  - 'jest.config.js'
  - 'logs/**/*'
  - 'node_modules/**/*'
  - 'yarn.lock'
