name: Deploy Test

on:
  push:
    branches:
      - deploy-action

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Make Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: cat /home/${{ secrets.DEPLOY_USERNAME }}/README.md
